name: relieflink
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^8.1.1

  flutter_map_tile_caching: ^10.1.1
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  cupertino_icons: ^1.0.8
  latlong2: ^0.9.1
  flutter_blue_plus: ^1.35.4
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Add assets here if needed
  # assets:
  #   - assets/images/
